# Generated by Django 3.0.4 on 2020-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nom')),
                ('phone', models.CharField(max_length=10, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
            ],
        ),
    ]
