# Generated by Django 3.0.4 on 2020-03-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivery', 'Delivery')], max_length=200, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nom du produit')),
                ('price', models.FloatField(null=True, verbose_name='Prix du produit')),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True, verbose_name='Categorie du produit')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Description du produit')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
    ]
